In [1]:
import pandas as pd

In [81]:
df= pd.read_csv("carprices.csv")
df

                Car Model  Mileage  Sell Price($)  Age(yrs)
0                  BMW X5    69000          18000         6
1                  BMW X5    35000          34000         3
2                  BMW X5    57000          26100         5
3                  BMW X5    22500          40000         2
4                  BMW X5    46000          31500         4
5                 Audi A5    59000          29400         5
6                 Audi A5    52000          32000         5
7                 Audi A5    72000          19300         6
8                 Audi A5    91000          12000         8
9   Mercedez Benz C class    67000          22000         6
10  Mercedez Benz C class    83000          20000         7
11  Mercedez Benz C class    79000          21000         7
12  Mercedez Benz C class    59000          33000         5

In [82]:
dummy = pd.get_dummies(df["Car Model"]).astype(int)
dummy

    Audi A5  BMW X5  Mercedez Benz C class
0         0       1                      0
1         0       1                      0
2         0       1                      0
3         0       1                      0
4         0       1                      0
5         1       0                      0
6         1       0                      0
7         1       0                      0
8         1       0                      0
9         0       0                      1
10        0       0                      1
11        0       0                      1
12        0       0                      1

In [83]:
merge = pd.concat([df,dummy], axis="columns")
merge

,Car Model,Mileage,Sell Price($),Age(yrs),Audi A5,BMW X5,Mercedez Benz C class
0,BMW X5,69000,18000,6,0,1,0
1,BMW X5,35000,34000,3,0,1,0
2,BMW X5,57000,26100,5,0,1,0
3,BMW X5,22500,40000,2,0,1,0
4,BMW X5,46000,31500,4,0,1,0
5,Audi A5,59000,29400,5,1,0,0
6,Audi A5,52000,32000,5,1,0,0
7,Audi A5,72000,19300,6,1,0,0
8,Audi A5,91000,12000,8,1,0,0
9,Mercedez Benz C class,67000,22000,6,0,0,1
10,Mercedez Benz C class,83000,20000,7,0,0,1
11,Mercedez Benz C class,79000,21000,7,0,0,1
12,Mercedez Benz C class,59000,33000,5,0,0,1

In [84]:
final = merge.drop(["Car Model"], axis="columns")
final

    Mileage  Sell Price($)  Age(yrs)  Audi A5  BMW X5  Mercedez Benz C class
0     69000          18000         6        0       1                      0
1     35000          34000         3        0       1                      0
2     57000          26100         5        0       1                      0
3     22500          40000         2        0       1                      0
4     46000          31500         4        0       1                      0
5     59000          29400         5        1       0                      0
6     52000          32000         5        1       0                      0
7     72000          19300         6        1       0                      0
8     91000          12000         8        1       0                      0
9     67000          22000         6        0       0                      1
10    83000          20000         7        0       0                      1
11    79000          21000         7        0       0                      1
12    59000          33000         5        0       0                      1

In [85]:
new_final = final.drop(["Mercedez Benz C class"], axis="columns")
new_final

    Mileage  Sell Price($)  Age(yrs)  Audi A5  BMW X5
0     69000          18000         6        0       1
1     35000          34000         3        0       1
2     57000          26100         5        0       1
3     22500          40000         2        0       1
4     46000          31500         4        0       1
5     59000          29400         5        1       0
6     52000          32000         5        1       0
7     72000          19300         6        1       0
8     91000          12000         8        1       0
9     67000          22000         6        0       0
10    83000          20000         7        0       0
11    79000          21000         7        0       0
12    59000          33000         5        0       0

In [86]:
X= new_final.drop(["Sell Price($)"], axis="columns")
X

    Mileage  Age(yrs)  Audi A5  BMW X5
0     69000         6        0       1
1     35000         3        0       1
2     57000         5        0       1
3     22500         2        0       1
4     46000         4        0       1
5     59000         5        1       0
6     52000         5        1       0
7     72000         6        1       0
8     91000         8        1       0
9     67000         6        0       0
10    83000         7        0       0
11    79000         7        0       0
12    59000         5        0       0

In [87]:
y = df["Sell Price($)"]
y

0     18000
1     34000
2     26100
3     40000
4     31500
5     29400
6     32000
7     19300
8     12000
9     22000
10    20000
11    21000
12    33000
Name: Sell Price($), dtype: int64

In [88]:
from sklearn import linear_model

In [89]:
model = linear_model.LinearRegression()
model

LinearRegression()

In [90]:
model.fit(X,y)

LinearRegression()

In [91]:
model.predict(X)

array([18705.2723644 , 35286.78445645, 24479.19112468, 41245.76426391,
       29882.98779056, 28023.6135243 , 30614.46818502, 21879.57266964,
       12182.34562104, 26183.72387884, 18929.31674102, 20409.80511857,
       30477.15426156])

In [92]:
model.score(X,y)

0.9417050937281082

In [93]:
model.predict([[45000,4,0,0]])

C:\Users\bhati\Desktop\py-library\.venv\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([36991.31721061])

In [94]:
model.predict([[86000,7,0,1]])

C:\Users\bhati\Desktop\py-library\.venv\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([11080.74313219])

In [112]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

dlf = df.copy()   # safer than assigning directly
dlf["Car Model"] = le.fit_transform(dlf["Car Model"])
dlf

    Car Model  Mileage  Sell Price($)  Age(yrs)
0           1    69000          18000         6
1           1    35000          34000         3
2           1    57000          26100         5
3           1    22500          40000         2
4           1    46000          31500         4
5           0    59000          29400         5
6           0    52000          32000         5
7           0    72000          19300         6
8           0    91000          12000         8
9           2    67000          22000         6
10          2    83000          20000         7
11          2    79000          21000         7
12          2    59000          33000         5

In [113]:
X = dlf[["Car Model","Mileage","Age(yrs)"]].values
X

array([[    1, 69000,     6],
       [    1, 35000,     3],
       [    1, 57000,     5],
       [    1, 22500,     2],
       [    1, 46000,     4],
       [    0, 59000,     5],
       [    0, 52000,     5],
       [    0, 72000,     6],
       [    0, 91000,     8],
       [    2, 67000,     6],
       [    2, 83000,     7],
       [    2, 79000,     7],
       [    2, 59000,     5]])

In [114]:
y = dlf["Sell Price($)"]
y

0     18000
1     34000
2     26100
3     40000
4     31500
5     29400
6     32000
7     19300
8     12000
9     22000
10    20000
11    21000
12    33000
Name: Sell Price($), dtype: int64

In [105]:
model = linear_model.LinearRegression()
model

LinearRegression()

In [109]:
model.fit(X,y)

LinearRegression()

In [110]:
model.predict(X)

array([22855.47176747, 36101.34690856, 27545.28569062, 40997.05248879,
       31823.31629959, 25620.04649333, 28502.52969256, 20518.449256  ,
       13197.73798059, 24780.71096476, 18443.76378491, 20090.89704162,
       27823.3916312 ])

In [111]:
model.predict([[45000,4,0,0]])

ValueError: X has 4 features, but LinearRegression is expecting 3 features as input.